board:
  # Number of rows
  n_rows: 6
  # Number of columns
  n_cols: 6

  # We use "idx" to indicate the situation of a grid.
  #   Idx 0 is the car that we have to accomplish solving this puzzle by
  #   move it to the specific position.

  # Define background and each car index's color.
  #   The string you type must be named color in matplotlib.
  #   Please refer to this page: https://matplotlib.org/stable/gallery/color/named_colors.html
  background_color: lightgray
  # Number of car colors you type below shows how many car you can use in the puzzle.
  #   The number of car colors must >= 1.
  car_colors:
    - red
    - aqua
    - yellow
    - greenyellow
    - orange
    - violet
    - darkolivegreen
    - brown
    - royalblue
    - paleturquoise
    - darkgoldenrod
    - hotpink
    - indigo
    - linen
    - olive
    - turquoise
    - violet
    - mediumslateblue

search_debug:
  show_part_info: true # bool
  n_loop_to_show_part_info: 5000
  n_visited_to_show_info: 5000 # Show n_visited, cur_node_num_in_container, and explored_list_len
  show_new_max_depth: true # bool